allow_remote_control yes
resize_debounce_time 0.1
placement_strategy center
confirm_os_window_close 0
font_family JetBrainsMono NFM

# BEGIN_KITTY_THEME
# Chalkboard
include current-theme.conf
# END_KITTY_THEME
